### PR TITLE
splash for ios is added

### PR DESCRIPTION
**Pull request by Azizadx**
### **The splash screen is added for ios**  
The image attached at bottom is how the splash screen looks like 

Screenshot 2023-01-29 at 11 57 09 AM

### CODE REVIEW

**Comment by Azizadx** [comment]
I don't like it though, what you think @nebiyuelias1

**Comment by nebiyuelias1** [comment]
@Azizadx I have actually closed the issue for this task. I also found a better image than the one we had. So you can see the change by pulling the latest changes and see if it works on iOS?

**Comment by Azizadx** [comment]
> @Azizadx I have actually closed the issue for this task. I also found a better image than the one we had. So you can see the change by pulling the latest changes and see if it works on iOS?

oh really that nice let me test then

**Comment by Azizadx** [comment]
@nebiyuelias1 cant run the app on ios did you use package or something to build splash for ios ?

**Comment by Azizadx** [comment]
Did you update the podfile

Screenshot 2023-01-29 at 1 55 51 PM

**Comment by nebiyuelias1** [comment]
> @nebiyuelias1 cant run the app on ios did you use package or something to build splash for ios ?

Yes, I did use a package. I hope it didn't affect the setup for iOS.

**Comment by Azizadx** [comment]
> > @nebiyuelias1 cant run the app on ios did you use package or something to build splash for ios ?
> 
> Yes, I did use a package. I hope it didn't affect the setup for iOS.

Well it did @nebiyuelias1  as you can see I made the minimum support ios 9.0 but somehow it been updated to ios 11.0

**Comment by Azizadx** [comment]
> > > @nebiyuelias1 cant run the app on ios did you use package or something to build splash for ios ?
> > 
> > 
> > Yes, I did use a package. I hope it didn't affect the setup for iOS.
> 
> Well it did @nebiyuelias1 as you can see I made the minimum support ios 9.0 but somehow it been updated to ios 11.0

it is a small bug we just need to reconfigure it on Xcode but I have a question for you, should we go with ios 9.0 or 11.0?

**Comment by Azizadx** [comment]
@nebiyuelias1 ios is building successfully now you can merge also splash screen package caused error for ios 9.0, so I make ios 11.0

**Pull request merged**
